### ISSUE TITLE
Reporting when package is published but docs fail can be confusing

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#270]
```
$ mix hex.publish
Passphrase:
Publishing gen_stage 0.4.2
  Files:
    lib/dynamic_supervisor.ex
    lib/gen_stage.ex
    lib/gen_stage/broadcast_dispatcher.ex
    lib/gen_stage/demand_dispatcher.ex
    lib/gen_stage/dispatcher.ex
    lib/gen_stage/flow.ex
    lib/gen_stage/flow/map_reducer.ex
    lib/gen_stage/flow/materialize.ex
    lib/gen_stage/partition_dispatcher.ex
    lib/gen_stage/streamer.ex
    mix.exs
    README.md
    CHANGELOG.md
  App: gen_stage
  Name: gen_stage
  Description: GenStage specification and computational flow for Elixir
  Version: 0.4.2
  Build tools: mix
  Licenses: Apache 2
  Links:
    GitHub: https://github.com/elixir-lang/gen_stage
  Elixir: ~> 1.3
  WARNING! Missing metadata fields: maintainers
  WARNING! Excluded dependencies (not part of the Hex package):
    ex_doc
    inch_ex
Before publishing, please read Hex Code of Conduct: https://hex.pm/policies/codeofconduct
Proceed? [Yn]
Compiling 10 files (.ex)
Generated gen_stage app
The "docs" task is unavailable. Please add {:ex_doc, ">= 0.0.0", only: :dev} to your dependencies in your mix.exs. If ex_doc was already added, make sure you run the task in the same environment it is configured to
** (Mix) The task "docs" could not be found. Did you mean "do"?
```

See the "Compiling 10 files (.ex)". It happens when generating the docs. After the package is published, I would add "Package published." and then "Now building docs.". Otherwise I would think both publishing the package and the docs failed. I would also improve the docs error message to say how to re-run the command _only_ for docs "mix hex.publish docs".

**Comment by ericmj** [comment]
I changed the order we run commands so that we do as much as possible locally before actually sending any requests to the API. So in this case the package was never published because the docs failed to build.

How can we improve the messaging?

**Comment by ericmj** [comment]
To clarify on my previous comments, this the new publish flow:

1. Build the package tarball and ask the user if we should proceed
2. Run the docs task
3. Publish package
4. Publish docs

https://github.com/hexpm/hex/blob/master/lib/mix/tasks/hex/publish.ex#L133-L139

**Comment by josevalim** [comment]
I would invert step 1 and 2. Otherwise you will possibly get lines about compilation *after* you ask to proceed and that can hide the warnings emitted by Hex.

**Comment by josevalim** [comment]
Improving the error message, I would just add the command:

> make sure you run the task in the same environment it is configured to with "mix hex.publish docs".

Btw, even with reordering the steps, I would make sure to write "Package published" before publishing the docs just in case publishing the docs fail. Or they would never work individually?

**Comment by ericmj** [comment]
Sounds good.

> Btw, even with reordering the steps, I would make sure to write "Package published" before publishing the docs just in case publishing the docs fail. Or they would never work individually?

I haven't tried it but we should be doing that. They are separate requests so it's possible that one fails but not the other.

**Comment by ericmj** [comment]
I have improved the messages slightly on master. Please check the commits referenced in this issue or verify the next time you publish a package :).

> I would invert step 1 and 2. Otherwise you will possibly get lines about compilation after you ask to proceed and that can hide the warnings emitted by Hex.

It won't hide the warnings because right after printing all package information we ask the user if he/she wants to proceed. I think reordering can also be confusing if you call `hex.publish` and you get compilation errors as the only output. With the new messages this should hopefully be better.

I am closing this but please reopen if you think it can be further improved.

**Comment by codeanpeace** [comment]
I just ran into this exact issue attempting to publish a hex package without ex_doc. I was uncertain whether it successfully published and ended up here searching for clarification.

It'd have been helpful for the output to explicitly say something to the effect that ex_doc is required before you can successfully publish your hex package.

**Comment by ericmj** [comment]
@codeanpeace Can you paste the output from hex when you published your package? And let us know which version you are running with `mix hex.info`.

**Comment by codeanpeace** [comment]
Of course!
Output from `mix hex.info`:
```
Hex:    0.16.0
Elixir: 1.4.2
OTP:    19.3

Built with: Elixir 1.4.2 and OTP 18.3.4.4
```

Output from `mix hex.publish`:
```
Passphrase:
Publishing ecto_conditionals 0.1.0
  Dependencies:
    ecto >= 0.0.0 (app: ecto)
  Files:
    lib/ecto_conditionals.ex
    mix.exs
    README.md
    LICENSE.md
  App: ecto_conditionals
  Name: ecto_conditionals
  Description: EctoConditionals implements a flexibly functional find_or_create and upsert behavior for Ecto models.
  Version: 0.1.0
  Build tools: mix
  Licenses: GPL 3.0
  Maintainers: h@rrison.us
  Links:
    GitHub: https://github.com/codeanpeace/ecto_conditionals
  Elixir: ~> 1.4
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct
Proceed? [Yn] Y
Building docs...
Compiling 1 file (.ex)
Generated ecto_conditionals app
The "docs" task is unavailable. Please add {:ex_doc, ">= 0.0.0", only: :dev} to your dependencies in your mix.exs. If ex_doc was already added, make sure you run the task in the same environment it is configured to
** (Mix) The task "docs" could not be found. Did you mean "do"?
```

**Comment by ericmj** [comment]
> It'd have been helpful for the output to explicitly say something to the effect that ex_doc is required before you can successfully publish your hex package.

This is what we do, from what you pasted:

> The "docs" task is unavailable. Please add {:ex_doc, ">= 0.0.0", only: :dev} to your dependencies in your mix.exs. If ex_doc was already added, make sure you run the task in the same environment it is configured to

**Comment by josevalim** [comment]
@ericmj To be clear, we say the task is unavailable and that you need it, but it may not be clear the status of publication. What about this:

```elixir
Publication failed because the "docs" task is unavailable. You may resolve this by:

  1. Adding {:ex_doc, ">= 0.0.0", only: :dev} to your dependencies in your mix.exs and trying again
  2. If ex_doc was already added, make sure you run "mix hex.publish" in the same environment as the ex_doc package
  3. Publishing the package without docs by running "mix hex.publish package" (not recommended)
```

?

**Comment by codeanpeace** [comment]
Precisely, my first line of thought was wondering whether the package could of been successfully published but just without docs.
